#!/bin/bash

# optional name for logging
name=hello_world!

# what user runs the bin
user=user

# interval in seconds
  # Note: 5 seconds is minimum by default
  # Other than regular format in seconds (as currently uncommented) you can also include basic mathematical operation for your convinience (it might take a tiny bit of performance though)
  # example:
  # intrv="60 * 60 * 24 * N" # where N is the number of days
intrv=60 # one minute
