#!/bin/bash

# optional name for logging
name=hello_world!

# what user runs the bin
user=user

# interval in seconds
# Note: 60 seconds is the minimum
# you can change the cron frequency to allow lower
intr=60
